### ISSUE TITLE
Value error when running example code

### ISSUE THREAD

**Issue by angoodkind** [rmcgibbo/logsumexp#5]
When I run the code in the example on the README, I get:
```
>>> sselogsumexp.logsumexp(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sselogsumexp.pyx", line 8, in sselogsumexp.logsumexp (sselogsumexp.c:1258)
ValueError: Buffer dtype mismatch, expected 'float32_t' but got 'double'
```
How can this be resolved?

**Comment by angoodkind** [comment]
This can be fixed by making `x` instead `x=x.astype(np.float32)`

**Comment by rmcgibbo** [comment]
Good catch. Would you like to make a pull request to fix it?
